#!/bin/sh -e

CONF_FILES='/etc/opush/sync_perms.ini
/etc/opush/ldap_conf.ini
/etc/opush/mail_conf.ini
/etc/opush/remote_console.ini
/etc/opush/policy.ini
/etc/opush/cassandra.ini
/etc/opush/logback.xml'

if [ $1 = 'purge' ]; then

  for file in $CONF_FILES
  do
    ucf --debconf-ok --purge $file
    ucfr --purge opush $file
    rm -rf $file
  done

  echo PURGE | debconf-communicate opush > /dev/null
  
  rm -rf /var/lib/opush
  rm -rf /var/run/opush
  rm -rf /var/log/opush
fi
