== Administration Operation

include::crash-usage.adoc[]

=== Device Reinitialization

Sometimes users may need to reset their devices.
This can be done by two different ways in *OBM*:

* by *obm-ui*: the *OBM* administrator has to delete the mobile device in the
	dedicated user page
* by the device itself: the device user has to modify the filter type
	(synchronization timeframe) in the ActiveSync account settings

Here is a list of devices which are known to be compatible with this
operation:

|=======================================================================
|*Device*				| *By obm-ui*	|*By device*	
|HTC HD Mini (Windows Mobile 6.5)	| [green]#YES#	| [green]#YES#	
|iPhone 4 (iOS 5.1.1)			| [green]#YES#	| [green]#YES#	
|iPad 3 (iOS 6.0.1)			| [green]#YES#	| [green]#YES#	
|Samsung GALAXY S (Android 2.3.4)	| [green]#YES#
	(need email application or device restart)	| [green]#YES#	
|Samsung GALAXY SII (Android 2.3.3)	| [green]#YES#
	(need email application or device restart)	| [green]#YES#	
|Samsung GALAXY SII (Android 4.0.3)	| [green]#YES#	| [green]#YES#	
|Samsung OMNIA 7 (Windows Phone 7.5)	| [green]#YES#	| [green]#YES#	
|=======================================================================

=== Supervision

We supply a probe called *Spushnik* to supervise your Opush server. See the
http://obm.org/content/spushnik[spushnik documentation] for more information.

== Opush Server Access

=== Reverse Proxy

The ActiveSync protocol defines specific URLs on standard https port for
devices to detect configuration and perform general operations. Opush runs
on port +8082+, therefore your web server needs to be configured to publish
Opush under the following URLs:

* +https://_your_server_/Microsoft-Server-ActiveSync+ for general operations
* +https://_your_server_/autodiscover+ (case may vary) for 
  <<_autodiscover,autoconfiguration feature>>

Packaging can create the appropriate Apache configuration to publish the Opush 
service under this URL. Nevertheless, you sometimes need to manage the reverse 
proxy configuration by yourself. In this case, be sure to bind 
+https://_your_apache_server_/Microsoft-Server-ActiveSync+ to 
+http://_your_opush_server_:8082/opush/ActiveSyncServlet/+ and
+https://_your_apache_server_/autodiscover+ to 
+http://_your_opush_server_:8082/opush/Autodiscover/+

WARNING: +autodiscover+ must be matched case-insensitive.

.Apache configuration directives
[source]
----
ProxyPass /Microsoft-Server-ActiveSync http://opush.domain:8082/opush/ActiveSyncServlet/
ProxyPassReverse /Microsoft-Server-ActiveSync http://opush.domain:8082/opush/ActiveSyncServlet/
ProxyPassMatch (?i:/autodiscover) http://opush.domain:8082/opush/Autodiscover/
ProxyPassReverse /autodiscover http://opush.domain:8082/opush/Autodiscover/
----

.Nginx configuration directives
[source]
----
server {
      listen 80 default;
      server_name _;
      location /Microsoft-Server-ActiveSync {
               proxy_pass http://opush.domain:8082/opush/ActiveSyncServlet/;
      }
      location /_autodiscover {
               proxy_pass http://opush.domain:8082/opush/Autodiscover/;
      }
      location ~* /autodiscover {
               rewrite ^ /_autodiscover last;
      }
}
----

=== DNS

When you try to add an ActiveSync account on your device, you must set the
user email address. +
When using <<_autodiscover,autoconfiguration feature>>, the domain part of the
email will be used to find the target server. +
It's necessary to have a DNS server configured to help the phone resolve
this domain. +

Some devices prefix the domain by +autodiscover.+. So you must add the following 
entries to your DNS configuration: 

 YOUR_DOMAIN                     A           YOUR_REVERSE_PROXY_SERVER_IP
 autodiscover.YOUR_DOMAIN        A           YOUR_REVERSE_PROXY_SERVER_IP

and for the reverse DNS part:

 YOUR_REVERSE_PROXY_SERVER_IP             A           YOUR_DOMAIN
 YOUR_REVERSE_PROXY_SERVER_IP             A           autodiscover.YOUR_DOMAIN

== Advanced Configuration

=== Mail Server

Opush needs an IMAP server running and a working IMAP account for every Opush
user. +
It also needs a working SMTP server.


==== Special Folders

ActiveSync defines some special folders: +Inbox+, +Drafts+, +Sent+ and
+Deleted+.

These folders are mapped to default IMAP folders that way:

|=======================================
| *ActiveSync folder* 	| *IMAP folder*	
| +Inbox+		| +INBOX+	
| +Drafts+		| +Drafts+	
| +Deleted+		| +Trash+	
| +Sent+		| +Sent+	
|=======================================

You can change these default mappings by defining the following keys in
+/etc/opush/mail_conf.ini+:

|===============================================
| *ActiveSync folder*	| *Configuration key*	
| +Drafts+		| +imap.mailbox.draft+	
| +Deleted+		| +imap.mailbox.sent+	
| +Sent+		| +imap.mailbox.trash+	
|===============================================

NOTE: the INBOX folder is not configurable because INBOX always exists as specified
by http://tools.ietf.org/html/rfc3501[IMAP RFC 3501], section 5.1.

.+/etc/opush/mail_conf.ini+ example:
****
imap.mailbox.draft=INBOX/draft +
imap.mailbox.sent=INBOX/sent +
imap.mailbox.trash=INBOX/trash +
****

===== Character Encoding
Non latin-1 characters are allowed but need special encoding.

You must use the +native2ascii+ tool provided by your JDK.

Given a mail_conf.ini encoded according to your locale, the following
command will generate a valid configuration:
[source]
----
$ native2ascii mail_conf.ini /etc/opush/mail_conf.ini
----

==== Mail Configuration

In addition to <<_special_folders,folder mapping configuration>>, there are
several things you can configure about Opush mail handling. +
Below is the default +/etc/opush/mail_conf.ini+ file:
[source]
----
include::sources/mail_conf.ini[]
----

|===============================================================================================================
| *Configuration key*		| *Value type*			| *Comments*					
| +imap.activateTLS+		| +boolean+ (true/false)	| Opush uses startTLS to secure IMAP
	 							  connection					
| +imap.loginWithDomain+	| +boolean+ (true/false)	| Opush includes @domain in login
								  for IMAP authentication			
| +imap.timeoutInMs+		| +milliseconds+		| timeout before Opush gives up an IMAP
								  command					
| +message.maxSize+		| +bytes+			| Max size allowed when sending a mail		
|===============================================================================================================

=== LDAP

==== About LDAP in Opush

In Opush, LDAP is used only for user lookups, depending on the clients requests.

Usually, it is used for recipient auto-completion when the user is writing an email.

[WARNING]
====
LDAP is neither used directly by Opush to populate the client address books nor
for authentication. These two features are delegated to obm-sync.
====

==== Configuration

The Opush LDAP configuration file is located at +/etc/opush/ldap_conf.ini+.

Every field is required and cannot be empty:

|===============================================================================================
| *Configuration key*	| *Value type*	| *Comments*						
| +search.ldap.filter+	| +String+	| The filter expression to use for the search		
| +search.ldap.url+	| +String+	| The address where the ldap server can be 
					  reached (we advise to specify the protocol
					  used, +ldap://+ or +ldaps://+)			
| +search.ldap.basedn+	| +String+	| The name of the context or object to search for	
|===============================================================================================


.+/etc/opush/ldap_conf.ini+ example
****
search.ldap.filter=(&(objectClass=inetOrgPerson) (|(mail=%q*)(sn=%q*)(givenName=%q*))) +
search.ldap.url=ldap://127.0.0.1 +
search.ldap.basedn=dc=%d,dc=local
****

==== Troubleshooting

You can check your LDAP configuration by looking at the logs when Opush starts.
You only have to activate the +CONFIGURATION+ logger, for more details check
the <<_logs,logs documentation section>>.


=== Autodiscover

The Autodiscover feature allows devices to detect the correct configuration 
based on the user's email address.

This feature requires a secure communication channel between the device and the
server.

Although some devices do not require a valid certificate it is highly 
recommended to set up a valid SSL certificate.

[NOTE]
====
Microsoft specifications:

* http://msdn.microsoft.com/en-us/library/ee178639.aspx[Autodiscover Command]
* http://msdn.microsoft.com/en-us/library/ee159670.aspx[Protocol Examples]
====

==== Device Configuration Steps

===== Certificate

If you have a certificate signed by a trusted authority, Autodiscover should
work out of the box.

For self-signed certificates, you need to import this certificate on
each device. Please refer to your device documentation for more details.

===== Account Creation

. In the _Accounts_ section of your device, create an _Exchange ActiveSync_ 
  account
. Configure only your e-mail and your password
. Your phone should now be configured for your account. That's all!


===== Compatibility

|===============================================================================
|*Device*		|*ROM / Version*	|*Compatibility*		
|HTC SAGA SENSE 3.0	|Orange / Android 2.3.5 |[green]#YES#			
|IPHONE 4		|IOS 5.1.1		|[green]#YES#			
|IPAD 3			|IOS 6.0.1		|[green]#YES#			
|SAMSUNG GALAXY S	|Orange / Android 2.3.4	|[red]#NO#			
|SAMSUNG GALAXY SII	|Orange / Android 4.0.3	|[red]#NO#			
|SAMSUNG GALAXY SII	|Orange / Android 2.3.3	|[red]#Not implemented by the phone#
|SAMSUNG OMNIA 7	|Windows phone 7.5	|[red]#NO#			
|===============================================================================

==== Underlying Protocol

A request looks like:

   <Request>
     <EMailAddress>chris@woodgrovebank.com</EMailAddress>
     <AcceptableResponseSchema>
       http://schemas.microsoft.com/exchange/autodiscover/mobilesync/responseschema/2006
     </AcceptableResponseSchema>
   </Request>

And a response:

   <Autodiscover>
      <Response>
         <Culture>fr:fr</Culture>
         <User>
            <EMailAddress>chris@woodgrovebank.com</EMailAddress>
         </User>
         <Action>
            <Settings>
               <Server>
                  <Type>MobileSync</Type>
                  <Url>https://as.woodgrovebank.com/Microsoft-Server-ActiveSync</Url>
                  <Name>https://as.woodgrovebank.com/Microsoft-Server-ActiveSync</Name>
               </Server>
               <Server>
                  <Type>CertEnroll</Type>
                  <Url>https://as.woodgrovebank.com/Microsoft-Server-ActiveSync</Url>
                  <ServerData>CertEnrollTemplate</ServerData>
               </Server>
            </Settings>
         </Action>
      </Response>
   </Autodiscover>

WARNING: You need to configure your server according to
<<_opush_server_access>> in order to have Autodiscover working

== Logs

Opush generates several log files located at +/var/log/opush/+:

 * +opush.log+ contains the main server logs
 * +access.log+ contains the http logs using the Apache default format
 * +out.log+ contains startup and uncatched errors

=== +opush.log+

This file contains important information about Opush operations.

Here is a sample line:
[source]
----
05:26:36.669 [INFO] {IMAP.COMMAND} [t10079/cFolderSync/r942/userlogin@obm.lng.org]:message content
----

It's composed of:

* +05:26:36.669+: The time of this log entry
* +[INFO]+: Log entry level
* +{IMAP.COMMAND}+: Logger name for this entry
* +t10079+: Thread id writing this log entry prefixed by t
* +cFolderSync+: The ActiveSync command name prefixed by c.
			Here the command was "FolderSync"
* +r942+: Request id prefixed by "r"
* +userlogin@obm.lng.org+: User causing this log entry
* +message content+: Logged data

=== Loggers

Opush, like all *Java* components of *OBM*, uses a logging API to generate information
useful to developers to investigate bugs. This section documents how to
configure the right log level for your needs as an administrator. +
Loggers exist in two forms: named loggers and technical loggers. +
Technical loggers have names related to the code they belong to and should
not be enabled by an administrator. +
Named loggers help administrators to understand what happens in their server in
order to solve some configuration problem or file a bug report. +
Opush will output every log with a level greater or equals to +WARN+,
regardless of the logger name. +
You can enable these named loggers by adding entries in 
+/etc/opush/logback.xml+. +
Modifications are taken into account every minute. You can check that everything
is applied correctly by looking at logs in +/var/log/opush/out.log+. +

.A sample file looks like:
    <included>
            <logger name="AUTHENTICATION" level="INFO" />
            <logger name="REQUEST.FULL" level="INFO" />
    </included>

You can use the following logger modules:

* +AUTHENTICATION+ for authentication information
* +BREAKDOWN+ for execution timings
* +CONFIGURATION+ for configuration details, printed at application startup
* +CONTAINER+ for the HTTP Servlet Container information
* +IMAP.COMMAND+ for imap conversations
* +OBM-SYNC+ for data exchanged between opush and obm-sync web services
* +REQUEST.FULL+ for requests and responses from and to the server,
	with sensitive data
* +REQUEST.TRIMMED+ for requests and responses from and to the server,
	without sensitive data
* +SUMMARY.IN+ for a summary of changes contained in an incoming request from the server point of view
* +SUMMARY.OUT+ for a summary of changes contained in an outgoing request from the server point of view


=== +BREAKDOWN+ Logs

Requests execution timings are tracked by Opush. It records the time spent in every category that compose the request life-cycle.

[source]
----
REQUEST:1147 (EMAIL:1095 (CASSANDRA:16, SQL:3, OTHER:1076), CASSANDRA:14, SQL:11, OTHER:27)
----

You have to read the +BREAKDOWN+ log line above as a tree where levels are separated by parentheses. +
It is easy to understand with some explanations:

* +REQUEST:1147+ means that the whole request execution took *1147ms* +
  ** +EMAIL:1095+: in *REQUEST*, *1095ms* have been spent in the *EMAIL* category +
    *** +CASSANDRA:16+: in *EMAIL*, *16ms* have been spent in the *CASSANDRA* category +
    *** +SQL:3+: in *EMAIL*, *3ms* have been spent in the *SQL* category +
    *** +OTHER:1076+: in *EMAIL*, *1076ms* have been spent executing code in the remaining categories  +
  ** +CASSANDRA:14+: in *REQUEST*, *14ms* have been spent in the *CASSANDRA* category +
  ** +SQL:11+: in *REQUEST*, *11ms* have been spent in the *SQL* category +
  ** +OTHER:27+: in *REQUEST*, *27ms* have been spent executing code in the remaining categories  +

Interpretation of these values can be useful to understand performance metrics of your Opush server. +
What is interesting in this example is +OTHER:1076+, it means that 1076ms has been spent in unnamed code category of *EMAIL*. +
It might be the imap server taking very long to process the Opush requests.

There are few fundamental rules that can be considered for better performance analysis:

* The first category is always *REQUEST*
* Duration of a category is always the sum of its children
* A branch of the tree can only have one occurrence of each category
* Children of a category are ordered by descending duration except for the +OTHER+ entry that is always the last

=== +SUMMARY.*+ Logs

A summary log looks like this :

[source]
----
11:46:03.976 [INFO ] {SUMMARY.OUT} [t106/cSync/r164/user@domain] CHANGE: 10, DELETE: 2, FETCH: 0
----

The three fields are always present even when the actual value is 0.

* +CHANGE+ counts the added or changed objects
* +DELETE+ counts the removed objects
* +FETCH+ counts the retrieved objects

This log is written for every request that retrieve or modify some data.
