== Architecture

Opush can be seen as a connector that provides ActiveSync support to *OBM*.

It requires several *OBM* services:

* *obm-locator* for locating *OBM* services
* *obm-sync* for calendar and addressbook synchronization
* *LDAP* for user lookup
* *Cyrus* for email synchronization
* *Postfix* for sending emails
* *Postgres* as a database backend

Additionally there are some technical dependencies:

* *Cassandra* for storing the internal state
* *OpenJDK 7*

=== ActiveSync Protocol

The Microsoft definition of objects such as events, contacts or emails differ 
from the *OBM* representation. Opush closes this gap by providing an ActiveSync 
frontend to *OBM*.

For this purpose, when a synchronization request comes from a device,
Opush analyzes this request, looks for *OBM* service locations and delegates data
retrieval to *Cyrus*, *obm-sync* and/or *LDAP*.

It then keeps track of objects pushed to the device to handle subsequent
synchronization requests. It uses *Cassandra* and *Postgres* for this purpose.

=== Technical Overview

Opush is a *Java* application using an embedded http server.

It uses a modular design that allows shifting technology without breaking
the whole application every time.

Recently, Opush has changed the email backend from an in-house solution to
a javax.mail based backend and then returned to an improved version of the
in-house solution.

It also changed from *EHCache* to *Cassandra* for internal state storage.

We expect to continue with such breaking changes for some times, improving our 
capabilities such as *high availability*, *horizontal scalability*,
*improved management*, *great monitoring*, and support for latest
ActiveSync specifications.
