== How to Configure Cassandra

=== Requirements

  * *Cassandra* 2.0, version >= 2.0.6
  * At least 2GiB of RAM
  * The *Cassandra* cluster must be installed (guides for
http://www.datastax.com/documentation/cassandra/2.0/cassandra/install/installDeb_t.html[Debian]
and
http://www.datastax.com/documentation/cassandra/2.0/cassandra/install/installRHEL_t.html[RHEL])
and http://www.datastax.com/documentation/cassandra/2.0/cassandra/initialize/initializeSingleDS.html[configured]

WARNING: Despite what datastax documentation says, *Cassandra* works well on OpenJDK 7

=== Supported Cassandra Configurations

[NOTE]
====
A single *Cassandra* server is enough to make Opush work but you will not have
every benefit of a *Cassandra* cluster. If you want the strongest architecture
you will have to deploy at least 3 nodes to have durability and fault-tolerance.
====

==== Three Nodes (recommended)

First of all, we advise you to read those two pages:

  * http://www.datastax.com/documentation/cassandra/2.0/cassandra/initialize/initializeSingleDS.html[Initializing a cluster]
  * http://www.datastax.com/documentation/cassandra/2.0/cassandra/architecture/architectureDataDistributeReplication_c.html?scroll=concept_ds_yt4_m4f_fk[Data replication]

Then, you will have to create your keyspace with a +replication_factor+ set to 3. +
Finally, you will have to set the +seeds+ and +rpc_address+ in your three +/etc/cassandra/cassandra.yaml+ files.

The example below is based on three servers with IPs +192.168.56.1+, +192.168.56.2+ & +192.168.56.3+, and a single +seed+.

.+/etc/cassandra/cassandra.yaml+ example on +192.168.56.1+
****
----
...
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "192.168.56.1"
...
rpc_address: 192.168.56.1
....
----
****
.+/etc/cassandra/cassandra.yaml+ example on +192.168.56.2+
****
----
...
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "192.168.56.1"
...
rpc_address: 192.168.56.2
....
----
****
.+/etc/cassandra/cassandra.yaml+ example on +192.168.56.3+
****
----
...
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "192.168.56.1"
...
rpc_address: 192.168.56.3
....
----
****


==== Single Node

For small configurations (number of users lower than 40), you may want to install *Cassandra* on a single node. +
Such case is discussed in this http://planetcassandra.org/blog/post/cassandra-faq-can-i-start-with-a-single-node/[article].

Your keyspace +replication_factor+ must be set to 1, 
and you must reduce your +commitlog_sync_period_in_ms+ which is configured in the +/etc/cassandra/cassandra.yaml+ file. +
Finally, you will have to set the +seeds+ and +rpc_address+ in your +/etc/cassandra/cassandra.yaml+ file.

.+/etc/cassandra/cassandra.yaml+ example on +192.168.56.1+
****
----
...
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "192.168.56.1"
...
rpc_address: 192.168.56.1
....
----
****

=== Preparing for Opush

Authentication in *Cassandra* must be delegated to the password authenticator backend, 
you have to edit the +/etc/cassandra/cassandra.yaml+ file and check the authenticator backend:

[source]
----
authenticator: PasswordAuthenticator
----

First of all, you have to create a keyspace. +
This must be done in the +cqlsh+ shell with *Cassandra* administrator:
[source]
----
$ cqlsh -u cassandra -p cassandra
---- 

And then enter the following command in the +cqlsh+ shell:
[source]
----
cqlsh> CREATE KEYSPACE opush_keyspace WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 3};
----
Where:

  * +opush_keyspace+ is the keyspace name
  * +replication_factor+ is documented on the <<_supported_cassandra_configurations, section>>  
  
Finally, still in the +cqlsh+ shell, create a *Cassandra* user for Opush:
[source]
----
cqlsh> USE opush_keyspace;
cqlsh> CREATE USER opush_user WITH PASSWORD 'opush_password' SUPERUSER;
----
Where:

  * +opush_user+ is the *Cassandra* user for Opush
  * +opush_password+ is the password for this user


=== Opush Schema

==== Installation

The first time you will start Opush, <<__code_opush_log_code,+opush.log+>> will
contain the following message:
[source]
----
10:49:48.611 [ERROR] {CONTAINER} [t/c/r/] Cassandra schema not installed, starting administration services only
----

Opush server will not be accessible to clients, but the administrator can connect 
using the <<_administration_with_the_strong_crash_strong_console, *CRaSH*>> shell. +
Furthermore you have to execute the +schema install+ <<crash-usage.adoc#_commands, *CRaSH*>> 
command and then restart Opush.

==== Upgrade

There are two kinds of schema upgrades:

===== Upgrade Recommended
The following message will be displayed in <<__code_opush_log_code,+opush.log+>>:
[source]
----
11:35:43.461 [WARN ] {CONTAINER} [t/c/r/] Cassandra schema not up-to-date, update is recommended
----

To upgrade, you should use the +schema update+ <<crash-usage.adoc#_commands, *CRaSH*>> command. Restarting Opush is not required for this type of upgrade.

NOTE: Clients can access Opush even if upgrade is recommended.


===== Upgrade Required
The following message will be displayed in <<__code_opush_log_code,+opush.log+>>:
[source]
----
11:43:51.857 [ERROR] {CONTAINER} [t/c/r/] Cassandra schema too old, starting administration services only
----

For required upgrades, you should use the +schema update+ <<crash-usage.adoc#_commands, *CRaSH*>> command and then restart Opush.

NOTE: Opush server will not be accessible to clients until restart.

