== Debian - Upgrade from Opush 2

[NOTE]
====
.If you want to install Opush 3 on the same machine as *OBM* 2.5.X
This Opush version is compatible with *OBM* 2.5.X but you may run into package
dependency issues.
Such *OBM* versions officialy support Debian Squeeze, however Opush requires
*OpenJDK 7* which is only available for Wheezy. +
Please follow this upgrade process <<_opush_on_squeeze_upgrade>>
====

=== System Requirements

  * *Debian Squeeze* or *Wheezy*
  * *OpenJDK 7*
  * A working http://obm.org/wiki/install-obm-debian-squeeze[*OBM*] >= 2.5.7 
	with Opush and *obm-sync*
  * A running <<_cassandra_setup,*Cassandra*>>

=== Package Dependency Conflicts

As +obm-full-2.5.X+ depends on +opush-2.5.X+, the installation of Opush 3
conflicts with +obm-full-2.5.X+. +
+obm-full+ is a meta-package only used to simplify installation of all *OBM*
packages. +
If you have it installed, it will be removed automatically when upgrading to 
the new version of Opush. This will not affect the functionality of *OBM*.

During the upgrade +apt-get+ will ask for confirmation before removing conflicting packages. As these are dependencies of Opush 2 only, packages listed below will be removed. No other removal should be necessary.

[source]
----
The following packages will be REMOVED:
  jetty obm-full obm-jetty obm-jetty-common-libs
----

=== Opush on Wheezy Upgrade

Modify your +/etc/apt/sources.list+ file by adding the Opush repository:
[source]
----
deb http://deb.obm.org/opush/stable opush opush
----

Update system packages list:
[source]
----
$ aptitude update
----

Finally, upgrade Opush:
[source]
----
$ aptitude install opush
----


You will be asked to remove some packages:
[source]
----
The following NEW packages will be installed:
  ca-certificates-java{a} icedtea-7-jre-jamvm{a} libnspr4{a} libnss3{a} libpcsclite1{a} openjdk-7-jre-headless{a} openjdk-7-jre-lib{a} tzdata-java{a} 
The following packages will be upgraded:
  opush{b} tzdata 
2 packages upgraded, 8 newly installed, 0 to remove and 69 not upgraded.
Need to get 43.6 MB/78.6 MB of archives. After unpacking 56.9 MB will be used.
The following packages have unmet dependencies:
 opush : Conflicts: obm-jetty but 2.5.7 is installed.
         Conflicts: jetty but 6.1.26-1 is installed.
The following actions will resolve these dependencies:

     Remove the following packages:
1)     jetty                       
2)     obm-jetty                   
3)     obm-jetty-common-libs       



Accept this solution? [Y/n/q/?] 
----

Go ahead and accept this solution by answering with *Y*.

Afterwards, accept the newly installed packages:
[source]
----
The following NEW packages will be installed:
  ca-certificates-java{a} icedtea-7-jre-jamvm{a} libnspr4{a} libnss3{a} libpcsclite1{a} openjdk-7-jre-headless{a} openjdk-7-jre-lib{a} tzdata-java{a} 
The following packages will be REMOVED:
  jetty{a} jsvc{u} libcommons-daemon-java{u} libjetty-java{u} libservlet2.5-java{u} libslf4j-java{u} obm-jetty{a} obm-jetty-common-libs{a} spushnik{a} 
The following packages will be upgraded:
  opush tzdata 
2 packages upgraded, 8 newly installed, 9 to remove and 68 not upgraded.
Need to get 43.6 MB/78.6 MB of archives. After unpacking 30.3 MB will be used.
Do you want to continue? [Y/n/?] 
----

=== Opush on Squeeze Upgrade

Modify your +/etc/apt/sources.list+ file by adding the Opush and squeeze-backports repositories:
[source]
----
deb http://deb.obm.org/opush/stable opush opush
deb http://deb.obm.org/squeeze-backports squeeze main
----

Update the system packages list:
[source]
----
$ apt-get update
----

.If you have the +obm-full+ package installed 
To upgrade Opush when you have +obm-full+ installed, please read the <<_package_dependency_conflicts>> to understand what will be done with your 
*OBM* packages.

To resolve conflicts properly use +apt-get+ instead of +aptitude+ and install
explicitly every +obm-full+ dependency to be sure to keep everything.

[source]
----
$ apt-get install opush obm obm-filter obm-satellite obm-sync obm-storage obm-ldap obm-ui obm-cyrus obm-postfix obm-services obm-locator obm-solr
----

.If you don't have obm-full installed:

[source]
----
$ apt-get install opush
----


=== Configuration with Debconf

During the installation process, you will be asked some questions:

  * +Authorize synchronization of unknown devices by default+ true/false
  * +Opush Cassandra seeds+ List of *Cassandra* seeds (IPs), separated by comas
  * +Opush Cassandra keyspace+ *Cassandra* keyspace for Opush
  * +Opush Cassandra user+ *Cassandra* user for Opush
  * +Opush Cassandra user password+ *Cassandra* user password for Opush

Answering these questions will modify the following configuration files:

  * +/etc/opush/cassandra.ini+
  * +/etc/opush/sync_perms.ini+

.Sample configuration +/etc/opush/cassandra.ini+
****
cassandra.seeds=192.168.56.4,192.168.56.5,192.168.56.6 +
cassandra.keyspace=opush +
cassandra.user=opush +
cassandra.password=opush +
****

.Sample configuration +/etc/opush/sync_perms.ini+
****
# If you set to false, pda can't sync with obm without validation by +
# an administrator on OBM interface. +
allow.unknown.pda=true +
****

include::follow-opush-cassandra-schema.adoc[]
