== Debian - Opush Installation

[NOTE]
====
.If you want to install Opush 3 on the same machine as *OBM* 2.5.X
This Opush version is compatible with *OBM* 2.5.X but you may run into package dependency issues. 
Such *OBM* versions officialy support Debian Squeeze, however Opush requires 
*OpenJDK 7* which is only available for Wheezy. +
Please follow this installation process <<_opush_on_squeeze_installation>>
====

=== System Requirements

  * *Debian Squeeze* or *Wheezy*
  * *OpenJDK 7*
  * A working http://obm.org/wiki/install-obm-debian-squeeze[*OBM*] >= 2.5.7 
	with *obm-sync*
  * A running <<_cassandra_setup,*Cassandra*>>

=== Opush on Wheezy Installation

Modify your +/etc/apt/sources.list+ file by adding the Opush repository:
[source]
----
deb http://deb.obm.org/opush/stable opush opush
----

Add the *OBM* GPG public key:
[source]
----
$ wget -q  http://deb.obm.org/obmgpg.pub -O - | apt-key  add -
----

Update the system packages list:
[source]
----
$ aptitude update
----

And finally, install Opush
[source]
----
$ aptitude install opush
----

=== Opush on Squeeze Installation

[WARNING]
====
If you have the +obm-full+ package installed 
In this context you already have an Opush on your machine, please follow <<_debian_upgrade_from_opush_2>> instead.
====

Modify your +/etc/apt/sources.list+ file by adding the Opush and squeeze-backports repositories:
[source]
----
deb http://deb.obm.org/opush/stable opush opush
deb http://deb.obm.org/squeeze-backports squeeze main
----

Add the *OBM* GPG public key:
[source]
----
$ wget -q  http://deb.obm.org/obmgpg.pub -O - | apt-key  add -
----

Update the system packages list:
[source]
----
$ apt-get update
----

Install Opush:

[source]
----
$ apt-get install opush
----


=== Configuration with Debconf

During the installation process, you will be asked some questions:

  * +Host IP address for OBM database server+ Your *OBM* host
  * +Type of OBM database server+ Type of *OBM* database server
  * +OBM database name+ *OBM* database name
  * +OBM database user name+ *OBM* database user
  * +Host IP address for LDAP server+ URL of the *OBM* LDAP (_ldap://..._ or _ldaps://..._)
  * +External url of OBM+ Your *OBM* FQDN
  * +OBM database user password+ *OBM* database user password
  * +Authorize synchronization of unknown devices by default+ true/false
  * +Opush Cassandra seeds+ List of *Cassandra* seeds (IPs), separated by commas
  * +Opush Cassandra keyspace+ *Cassandra* keyspace for Opush
  * +Opush Cassandra user+ *Cassandra* user for Opush
  * +Opush Cassandra user password+ *Cassandra* user password for Opush

Answering these questions will modify the following configuration files:

  * +/etc/opush/opush.ini+
  * +/etc/opush/ldap_conf.ini+
  * +/etc/opush/cassandra.ini+
  * +/etc/opush/sync_perms.ini+

.Sample configuration +/etc/opush/opush.ini+
****
# +
# Locator & Database URL +
# +
host=192.168.56.3 +

# +
# Database section +
# +

# DB type MYSQL, PGSQL +
dbtype=PGSQL +

# Database name +
db=obm +

# DB user +
user=obm +

# DB user password +
password=obm +

# OBM external URL +
external-url=opushvm.lyon.lan +

# +
# Transaction timeout section +
# +

# Transaction timeout +
transaction-timeout=1 +

# Transaction timeout unit (milliseconds, seconds, minutes, hours) +
transaction-timeout-unit=minutes +

# Default window size +
window-size=50 +
****

.Sample configuration +/etc/opush/ldap_conf.ini+
****
search.ldap.filter=(&(objectClass=inetOrgPerson) (|(mail=%q*)(sn=%q*)(givenName=%q*))) +
search.ldap.url=ldap://192.168.56.3 +
search.ldap.basedn=dc=%d,dc=local +
# search.ldap.limit=100 +
****

.Sample configuration +/etc/opush/cassandra.ini+
****
cassandra.seeds=192.168.56.4,192.168.56.5,192.168.56.6 +
cassandra.keyspace=opush +
cassandra.user=opush +
cassandra.password=opush +
****

.Sample configuration +/etc/opush/sync_perms.ini+
****
# If you set to false, pda can't sync with obm without validation by +
# an administrator on OBM interface. +
allow.unknown.pda=true +
****

include::follow-opush-cassandra-schema.adoc[]
