==== Configuration of the Communication with *OBM* Components

===== Main Configuration

[NOTE]
====
Opush reads its configuration from +/etc/opush/opush.ini+ then from +/etc/obm/obm_conf.ini+. +
If you already have a +/etc/obm/obm_conf.ini+ configured on the Opush machine, you can safely drop or empty +/etc/opush/opush.ini+. +
Then you may skip this section.
====

You have to edit the main configuration file:
[source]
.+/etc/opush/opush.ini+
----
include::sources/opush.ini[]
----

And then replace the default values:

  * +@DBHOST@+: Your *OBM* host
  * +@DBTYPE@+: +PGSQL+ or +MYSQL+ (*OBM* database kind)
  * +@DBNAME@+: *OBM* database name
  * +@DBUSER@+: *OBM* database user
  * +@DBPASSWORD@+: *OBM* database user password
  * +@EXTERNALURL@+: Your *OBM* FQDN
  
.Sample configuration
****
# +
# Locator & Database URL +
# +
host=192.168.56.3 +

# +
# Database section +
# +

# DB type MYSQL, PGSQL +
dbtype=PGSQL +

# Database name +
db=obm +

# DB user +
user=obm +

# DB user password +
password=obm +

# OBM external URL +
external-url=opushvm.lyon.lan +

# +
# Transaction timeout section +
# +

# Transaction timeout +
transaction-timeout=1 +

# Transaction timeout unit (milliseconds, seconds, minutes, hours) +
transaction-timeout-unit=minutes +

# Default window size +
window-size=50 +
****

===== LDAP Configuration
You have to edit the LDAP configuration file:
[source]
.+/etc/opush/ldap_conf.ini+
----
include::sources/ldap_conf.ini[]
----

And then replace the default value:

  * +@LDAPSERVER@+: URL of the *OBM* LDAP server (_ldap://..._ or _ldaps://..._)

.Sample configuration
****
search.ldap.filter=(&(objectClass=inetOrgPerson) (|(mail=%q*)(sn=%q*)(givenName=%q*))) +
search.ldap.url=ldap://192.168.56.3 +
search.ldap.basedn=dc=%d,dc=local +
# search.ldap.limit=100 +
****

See <<_ldap>> for more information.

==== Configuration of the *Cassandra* Connection
 
Opush needs additional configuration in order to connect to http://cassandra.apache.org/[Cassandra].

You have to edit the *Cassandra* configuration file:
[source]
.+/etc/opush/cassandra.ini+
----
include::sources/cassandra.ini[]
----

And then replace values as followed:

  * +@SEEDS@+: List of *Cassandra* seeds (IPs), separated by comas
  * +@KEYSPACE@+: *Cassandra* keyspace for Opush
  * +@USER@+: *Cassandra* user for Opush
  * +@PWD@+: *Cassandra* user password for Opush
  
.Sample configuration 
****
cassandra.seeds=192.168.56.4,192.168.56.5,192.168.56.6 +
cassandra.keyspace=opush +
cassandra.user=opush +
cassandra.password=opush +
****

include::follow-opush-cassandra-schema.adoc[]
